<!DOCTYPE html>
<html>

  <head>
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <meta name="description" content="Gkumar10.GitHub.io : ">

    <link rel="stylesheet" type="text/css" media="screen" href="stylesheets/stylesheet.css">

    <title>Gkumar10.GitHub.io</title>
  </head>

  <body>

    <!-- HEADER -->
    <div id="header_wrap" class="outer">
        <header class="inner">
          <a id="forkme_banner" href="https://github.com/gkumar10">View on GitHub</a>

          <h1 id="project_title">Gkumar10.GitHub.io</h1>
          <h2 id="project_tagline"></h2>

        </header>
    </div>

    <!-- MAIN CONTENT -->
    <div id="main_content_wrap" class="outer">
      <section id="main_content" class="inner">
        <p></p>



<p>
</p>

<p></p>

<p></p>

<p></p>
<div>

<div id="background">
<h1>
<a id="background" class="anchor" href="#background" aria-hidden="true"><span class="octicon octicon-link"></span></a>Background</h1>
<p>Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively. These type of devices are part of the quantified self movement – a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it.</p>
</div>

<div id="goal">
<h1>
<a id="goal" class="anchor" href="#goal" aria-hidden="true"><span class="octicon octicon-link"></span></a>Goal</h1>
<p>Goal is to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants to predict the manner in which they did the exercise. This is the “classe” variable in the training set. We will use any of the other variables to predict with. The report describes how the model was built, how I used cross validation, what the out of sample error is.</p>
</div>

<div id="preprocessing">
<h1>
<a id="preprocessing" class="anchor" href="#preprocessing" aria-hidden="true"><span class="octicon octicon-link"></span></a>Preprocessing</h1>
<p>Load libraries and training data. Create training set with 60% of dataset. For cross-validation, we will partition testing set into 2 equal subsets.</p>
<pre><code>suppressWarnings(suppressMessages(library(caret)))
suppressWarnings(suppressMessages(library(randomForest)))
suppressWarnings(suppressMessages(library(rpart)))
suppressWarnings(suppressMessages(library(pROC)))
setwd("~/Coursera/Practical-Machine-Learning")

df &lt;- read.csv("pml-training.csv", na.strings=c("NA",""), header=TRUE)
inTrain &lt;- createDataPartition(df$classe, p=0.6, list=FALSE)
training &lt;- df[inTrain,]
testing &lt;- df[-inTrain,]
inSubTest &lt;- createDataPartition(testing$classe, p=0.5, list=FALSE)
sub_testing1 &lt;- testing[inSubTest,]
sub_testing2 &lt;- testing[-inSubTest,]</code></pre>
<p>The training set has 160 columns. Not all columns wil be useful since many have NA values. We will remove these columns now.</p>
<pre><code>training &lt;- training[, which(as.numeric(colSums(is.na(training)))==0)]</code></pre>
<p>We will also remove columns that are non-numerics or timestamps or near zero fractions.</p>
<pre><code>training &lt;- training[,-c(1:7)]
training &lt;- training[, -c(grep("^gyros", names(training)))]
training &lt;- training[complete.cases(training), ]</code></pre>
</div>

<div id="model-selection-and-training">
<h1>
<a id="model-selection-and-training" class="anchor" href="#model-selection-and-training" aria-hidden="true"><span class="octicon octicon-link"></span></a>Model selection and training</h1>
<p>We will use 2 two learning algorithms (rpart and rf) to compare accuracy and out of sample errors.</p>
<div id="recursive-partitioning-rpart">
<h3>
<a id="recursive-partitioning-rpart" class="anchor" href="#recursive-partitioning-rpart" aria-hidden="true"><span class="octicon octicon-link"></span></a>Recursive Partitioning (rpart)</h3>
<pre><code>modelFit_rpart &lt;- train(classe ~ ., data=training, method="rpart")
prediction_rpart &lt;- predict(modelFit_rpart, newdata=testing)
cfm_rpart &lt;- confusionMatrix(prediction_rpart, testing$classe)
cfm_rpart</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    A    B    C    D    E
##          A 2042  654  633  587  199
##          B   33  500   39  215  190
##          C  152  364  696  484  391
##          D    0    0    0    0    0
##          E    5    0    0    0  662
##
## Overall Statistics
##                                           
##                Accuracy : 0.4971          
##                  95% CI : (0.4859, 0.5082)
##     No Information Rate : 0.2845          
##     P-Value [Acc > NIR] : < 2.2e-16       
##                                           
##                   Kappa : 0.3423  
##  Mcnemar's Test P-Value : NA              
## 
## Statistics by Class:
## 
##                      Class: A Class: B Class: C Class: D Class: E
## Sensitivity            0.9149  0.32938  0.50877   0.0000  0.45908
## Specificity            0.6307  0.92462  0.78527   1.0000  0.99922
## Pos Pred Value         0.4962  0.51177  0.33349      NaN  0.99250
## Neg Pred Value         0.9491  0.85180  0.88331   0.8361  0.89135
## Prevalence             0.2845  0.19347  0.17436   0.1639  0.18379
## Detection Rate         0.2603  0.06373  0.08871   0.0000  0.08437
## Detection Prevalence   0.5245  0.12452  0.26600   0.0000  0.08501
## Balanced Accuracy      0.7728  0.62700  0.64702   0.5000  0.72915

</code></pre>
<p>Accuracy of model with rpart method is 0.4970686 or 49.71 %.</p>
<p>Out of sample error is 0.5029314. This is the error rate when the method is used on a new data set.</p>
</div>

<div id="random-forest-rf">
<h3>
<a id="random-forest-rf" class="anchor" href="#random-forest-rf" aria-hidden="true"><span class="octicon octicon-link"></span></a>Random Forest (rf)</h3>
<pre><code>modelFit_rf &lt;- train(classe ~ ., 
                                    data=training, 
                                    method="rf", 
                                    trControl = trainControl(method="cv", number=4)) 
=======
## Sensitivity            0.9167  0.26548  0.50950   0.0000  0.45978
## Specificity            0.6263  0.94532  0.75471   1.0000  0.99938
## Pos Pred Value         0.4937  0.53805  0.30490      NaN  0.99400
## Neg Pred Value         0.9498  0.84289  0.87932   0.8361  0.89149
## Prevalence             0.2845  0.19347  0.17436   0.1639  0.18379
## Detection Rate         0.2608  0.05136  0.08884   0.0000  0.08450
## Detection Prevalence   0.5282  0.09546  0.29136   0.0000  0.08501
## Balanced Accuracy      0.7715  0.60540  0.63211   0.5000  0.72958</code></pre>
<p>Accuracy of model with rpart method is 0.4854703 or 48.55 %.</p>
<p>Out of sample error is 0.5145297. This is the error rate when the method is used on a new data set.</p>
</div>

<div id="random-forest-rf">
<h3>
<a id="random-forest-rf-1" class="anchor" href="#random-forest-rf-1" aria-hidden="true"><span class="octicon octicon-link"></span></a>Random Forest (rf)</h3>
<pre><code>#modelFit_rf &lt;- randomForest(classe ~ ., data=training) 
modelFit_rf &lt;- train(classe ~ ., data=training, method="rf", trControl = trainControl(method="cv", number=4)) 
&gt;&gt;&gt;&gt;&gt;&gt;&gt; origin/master
prediction_rf &lt;- predict(modelFit_rf, newdata=testing)
cfm_rf &lt;- confusionMatrix(prediction_rf, testing$classe)
cfm_rf</code></pre>
<pre><code>
## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    A    B    C    D    E
##          A 2224   14    0    0    0
##          B    8 1485   12    0    5
##          C    0   16 1349   13    3
##          D    0    3    7 1272    4
##          E    0    0    0    1 1430
## 
## Overall Statistics
##                                           
##                Accuracy : 0.989           
##                  95% CI : (0.9865, 0.9912)
##     No Information Rate : 0.2845          
##     P-Value [Acc > NIR] : < 2.2e-16       
##                                           
##                   Kappa : 0.9861          
##  Mcnemar's Test P-Value : NA              
## 
## Statistics by Class:
## 
##                      Class: A Class: B Class: C Class: D Class: E
## Sensitivity            0.9964   0.9783   0.9861   0.9891   0.9917
## Specificity            0.9975   0.9960   0.9951   0.9979   0.9998
## Pos Pred Value         0.9937   0.9834   0.9768   0.9891   0.9993
## Neg Pred Value         0.9986   0.9948   0.9971   0.9979   0.9981
## Prevalence             0.2845   0.1935   0.1744   0.1639   0.1838
## Detection Rate         0.2835   0.1893   0.1719   0.1621   0.1823
## Detection Prevalence   0.2852   0.1925   0.1760   0.1639   0.1824
## Balanced Accuracy      0.9970   0.9872   0.9906   0.9935   0.9958
  
</code></pre>
<p>Accuracy of model with rf method is 0.989039 or 98.9 %.</p>
<p>Out of sample error is 0.010961.</p>

<p>Clearly rf method has better accuracy and way lower out of sample error rate. We will continue to use Random Forest (rf) as the learning algorithm to obtain better predictive performance and find best predictors for classe variable.</p>
<p>We will use variable importance evaluation function ‘varImp’ to assign each predictor with a separate variable importance. All measures of importance is scaled to have a maximum value of 100.</p>
<pre><code>varimp &lt;- varImp(modelFit_rf, varImp.train=FALSE)
plot(varimp, top=25)</code></pre>
<img src="http://gkumar10.github.io/Practical_Machine_Learning_Course_Project_files/figure-html/unnamed-chunk-6-1.png" alt="" width="672">
<p>The top 25 most important variables are: roll_belt, pitch_belt, yaw_belt, total_accel_belt, accel_belt_x, accel_belt_y, accel_belt_z, magnet_belt_x, magnet_belt_y, magnet_belt_z, roll_arm, pitch_arm, yaw_arm, total_accel_arm, accel_arm_x, accel_arm_y, accel_arm_z, magnet_arm_x, magnet_arm_y, magnet_arm_z, roll_dumbbell, pitch_dumbbell, yaw_dumbbell, total_accel_dumbbell, accel_dumbbell_x, accel_dumbbell_y, accel_dumbbell_z, magnet_dumbbell_x, magnet_dumbbell_y, magnet_dumbbell_z, roll_forearm, pitch_forearm, yaw_forearm, total_accel_forearm, accel_forearm_x, accel_forearm_y, accel_forearm_z, magnet_forearm_x, magnet_forearm_y, magnet_forearm_z</p>
<p>Next we will compute area under the ROC curve for each class against the predictor. The ROC curve is essentially a plot of true positive rate against the false positive rate at various threshold settings.</p>
<pre><code>RocImp &lt;- filterVarImp(x = training[, -ncol(training)], y = training$classe)
plot(RocImp)</code></pre>
<p><img src="http://gkumar10.github.io/Practical_Machine_Learning_Course_Project_files/figure-html/unnamed-chunk-7-1.png" alt="" width="672"></p>
</div>

<p></p>
</div>

<div id="model-testing-and-cross-validation">
<h1>
<a id="model-testing-and-cross-validation" class="anchor" href="#model-testing-and-cross-validation" aria-hidden="true"><span class="octicon octicon-link"></span></a>Model testing and cross-validation</h1>
<p>Let us now test the models against the two testing subsets created during pre-processing.</p>
<pre><code>prediction1 &lt;- predict(modelFit_rf, newdata=sub_testing1)
cfm1 &lt;- confusionMatrix(prediction1, sub_testing1$classe)

prediction2 &lt;- predict(modelFit_rf, newdata=sub_testing2)
cfm2 &lt;- confusionMatrix(prediction2, sub_testing2$classe)</code></pre>
The accuracy of model against testing subset 1 is: 0.9895488 or 98.95 %. Out of sample error is 0.0104512.
<p>The accuracy of model against testing subset 2 is: 0.9882743 or 98.83 %. Out of sample error is 0.0117257.</p>
<div id="references">
<h2>
<a id="references" class="anchor" href="#references" aria-hidden="true"><span class="octicon octicon-link"></span></a>References:</h2>
<ol>
<li>Variable Importance function: <a href="http://topepo.github.io/caret/varimp.html">http://topepo.github.io/caret/varimp.html</a>
</li>
<li>Models available in caret: <a href="http://topepo.github.io/caret/bytag.html">http://topepo.github.io/caret/bytag.html</a>
</li>
=======
<p>The accuracy of model against testing subset 1 is: 0.9941371 or 99.41 %. Out of sample error is 0.0058629.</p>
<p>The accuracy of model against testing subset 2 is: 0.9959215 or 99.59 %. Out of sample error is 0.0040785.</p>
<div id="references">
<h2>
<a id="references-1" class="anchor" href="#references-1" aria-hidden="true"><span class="octicon octicon-link"></span></a>References:</h2>
<ol>
<li>Variable Importance function: <a href="http://topepo.github.io/caret/varimp.html">http://topepo.github.io/caret/varimp.html</a>
</li>
<li>Models available in caret: <a href="http://topepo.github.io/caret/bytag.html">http://topepo.github.io/caret/bytag.html</a>
</li>
&gt;&gt;&gt;&gt;&gt;&gt;&gt; origin/master
</ol>
</div>

<p></p>
</ol>
</div>

<div id="end-of-course-project-writeup">
<h1>
<a id="end-of-course-project-writeup" class="anchor" href="#end-of-course-project-writeup" aria-hidden="true"><span class="octicon octicon-link"></span></a>End of course project writeup</h1>
<p>+++++++++++++++++++++++++++++++++++++++++++++</p>
<div id="below-code-is-for-course-project-submission">
<h3>
<a id="below-code-is-for-course-project-submission" class="anchor" href="#below-code-is-for-course-project-submission" aria-hidden="true"><span class="octicon octicon-link"></span></a>Below code is for course project submission</h3>
<pre><code>testFinal &lt;- read.csv("pml-testing.csv", header=TRUE)
x &lt;- sort(match(names(training), names(testFinal)))
testFinal &lt;- testFinal[,x]
answers &lt;- predict(modelFit_rf, testFinal)

pml_write_files = function(x){
  n = length(x)
  for(i in 1:n){
    filename = paste0("problem_id_",i,".txt")
    write.table(x[i],file=filename,quote=FALSE,row.names=FALSE,col.names=FALSE)
  }
}

pml_write_files(answers)</code></pre>
</div>

<p></p>
</div>

<p></p>
</div>







<p>
</p>
</div>
      </section>
    </div>

    <!-- FOOTER  -->
    <div id="footer_wrap" class="outer">
      <footer class="inner">
        <p>Published with <a href="http://pages.github.com">GitHub Pages</a></p>
      </footer>
    </div>

    

  </body>
</html>
